export enum MappedMarketStatus {
  ALL = 'ALL',
  STANDARD = 'STANDARD',
  IN_PLAY = 'IN_PLAY',
  LIVE_NOW = 'LIVE_NOW',
  VOIDED = 'VOIDED',
  WAITING_FOR_SETTLEMENT = 'WAITING_FOR_SETTLEMENT',
  SETTLED = 'SETTLED',
  READY_FOR_SETTLEMENT = 'READY_FOR_SETTLEMENT',
  READY_TO_CLOSE = 'READY_TO_CLOSE',
  READY_TO_VOID = 'READY_TO_VOID',
  UNKNOWN = 'UNKNOWN',
  INITIALIZING = 'INITIALIZING',
}

export const OPEN_MARKET_STATUSES = [
  MappedMarketStatus.STANDARD,
  MappedMarketStatus.IN_PLAY,
  MappedMarketStatus.LIVE_NOW,
];
